// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.0
// source: p3.proto

package protocol03

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *JoinGroup) Reset() {
	*x = JoinGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p3_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGroup) ProtoMessage() {}

func (x *JoinGroup) ProtoReflect() protoreflect.Message {
	mi := &file_p3_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGroup.ProtoReflect.Descriptor instead.
func (*JoinGroup) Descriptor() ([]byte, []int) {
	return file_p3_proto_rawDescGZIP(), []int{0}
}

type BroadcastAll struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *BroadcastAll) Reset() {
	*x = BroadcastAll{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p3_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastAll) ProtoMessage() {}

func (x *BroadcastAll) ProtoReflect() protoreflect.Message {
	mi := &file_p3_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastAll.ProtoReflect.Descriptor instead.
func (*BroadcastAll) Descriptor() ([]byte, []int) {
	return file_p3_proto_rawDescGZIP(), []int{1}
}

func (x *BroadcastAll) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type BroadcastSector struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetSector uint64 `protobuf:"varint,1,opt,name=targetSector,proto3" json:"targetSector,omitempty"`
	Data         []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *BroadcastSector) Reset() {
	*x = BroadcastSector{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p3_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastSector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastSector) ProtoMessage() {}

func (x *BroadcastSector) ProtoReflect() protoreflect.Message {
	mi := &file_p3_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastSector.ProtoReflect.Descriptor instead.
func (*BroadcastSector) Descriptor() ([]byte, []int) {
	return file_p3_proto_rawDescGZIP(), []int{2}
}

func (x *BroadcastSector) GetTargetSector() uint64 {
	if x != nil {
		return x.TargetSector
	}
	return 0
}

func (x *BroadcastSector) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// echoes the same data back to the sender:
type Echo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Echo) Reset() {
	*x = Echo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p3_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Echo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Echo) ProtoMessage() {}

func (x *Echo) ProtoReflect() protoreflect.Message {
	mi := &file_p3_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Echo.ProtoReflect.Descriptor instead.
func (*Echo) Descriptor() ([]byte, []int) {
	return file_p3_proto_rawDescGZIP(), []int{3}
}

func (x *Echo) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type GroupMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group           string           `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	PlayerTime      int64            `protobuf:"varint,2,opt,name=playerTime,proto3" json:"playerTime,omitempty"`
	ServerTime      int64            `protobuf:"varint,3,opt,name=serverTime,proto3" json:"serverTime,omitempty"`
	PlayerIndex     uint32           `protobuf:"varint,4,opt,name=playerIndex,proto3" json:"playerIndex,omitempty"`
	PlayerInSector  uint64           `protobuf:"varint,5,opt,name=playerInSector,proto3" json:"playerInSector,omitempty"`
	JoinGroup       *JoinGroup       `protobuf:"bytes,10,opt,name=joinGroup,proto3,oneof" json:"joinGroup,omitempty"`
	BroadcastAll    *BroadcastAll    `protobuf:"bytes,11,opt,name=broadcastAll,proto3,oneof" json:"broadcastAll,omitempty"`
	BroadcastSector *BroadcastSector `protobuf:"bytes,12,opt,name=broadcastSector,proto3,oneof" json:"broadcastSector,omitempty"`
	Echo            *Echo            `protobuf:"bytes,13,opt,name=echo,proto3,oneof" json:"echo,omitempty"`
}

func (x *GroupMessage) Reset() {
	*x = GroupMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p3_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMessage) ProtoMessage() {}

func (x *GroupMessage) ProtoReflect() protoreflect.Message {
	mi := &file_p3_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMessage.ProtoReflect.Descriptor instead.
func (*GroupMessage) Descriptor() ([]byte, []int) {
	return file_p3_proto_rawDescGZIP(), []int{4}
}

func (x *GroupMessage) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *GroupMessage) GetPlayerTime() int64 {
	if x != nil {
		return x.PlayerTime
	}
	return 0
}

func (x *GroupMessage) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *GroupMessage) GetPlayerIndex() uint32 {
	if x != nil {
		return x.PlayerIndex
	}
	return 0
}

func (x *GroupMessage) GetPlayerInSector() uint64 {
	if x != nil {
		return x.PlayerInSector
	}
	return 0
}

func (x *GroupMessage) GetJoinGroup() *JoinGroup {
	if x != nil {
		return x.JoinGroup
	}
	return nil
}

func (x *GroupMessage) GetBroadcastAll() *BroadcastAll {
	if x != nil {
		return x.BroadcastAll
	}
	return nil
}

func (x *GroupMessage) GetBroadcastSector() *BroadcastSector {
	if x != nil {
		return x.BroadcastSector
	}
	return nil
}

func (x *GroupMessage) GetEcho() *Echo {
	if x != nil {
		return x.Echo
	}
	return nil
}

var File_p3_proto protoreflect.FileDescriptor

var file_p3_proto_rawDesc = []byte{
	0x0a, 0x08, 0x70, 0x33, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0b, 0x0a, 0x09, 0x4a, 0x6f,
	0x69, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x22, 0x22, 0x0a, 0x0c, 0x42, 0x72, 0x6f, 0x61, 0x64,
	0x63, 0x61, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x49, 0x0a, 0x0f, 0x42,
	0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x53, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x22,
	0x0a, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x53, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x53, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x1a, 0x0a, 0x04, 0x45, 0x63, 0x68, 0x6f, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0xb2, 0x03, 0x0a, 0x0c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x26, 0x0a, 0x0e, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x53, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x53, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x12, 0x2d, 0x0a, 0x09, 0x6a, 0x6f, 0x69, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x48, 0x00, 0x52, 0x09, 0x6a, 0x6f, 0x69, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x88,
	0x01, 0x01, 0x12, 0x36, 0x0a, 0x0c, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x41,
	0x6c, 0x6c, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x42, 0x72, 0x6f, 0x61, 0x64,
	0x63, 0x61, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x48, 0x01, 0x52, 0x0c, 0x62, 0x72, 0x6f, 0x61, 0x64,
	0x63, 0x61, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x88, 0x01, 0x01, 0x12, 0x3f, 0x0a, 0x0f, 0x62, 0x72,
	0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x53, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x53,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x48, 0x02, 0x52, 0x0f, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61,
	0x73, 0x74, 0x53, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x12, 0x1e, 0x0a, 0x04, 0x65,
	0x63, 0x68, 0x6f, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x45, 0x63, 0x68, 0x6f,
	0x48, 0x03, 0x52, 0x04, 0x65, 0x63, 0x68, 0x6f, 0x88, 0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f,
	0x6a, 0x6f, 0x69, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x62, 0x72,
	0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x12, 0x0a, 0x10, 0x5f, 0x62,
	0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x53, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x42, 0x07,
	0x0a, 0x05, 0x5f, 0x65, 0x63, 0x68, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_p3_proto_rawDescOnce sync.Once
	file_p3_proto_rawDescData = file_p3_proto_rawDesc
)

func file_p3_proto_rawDescGZIP() []byte {
	file_p3_proto_rawDescOnce.Do(func() {
		file_p3_proto_rawDescData = protoimpl.X.CompressGZIP(file_p3_proto_rawDescData)
	})
	return file_p3_proto_rawDescData
}

var file_p3_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_p3_proto_goTypes = []interface{}{
	(*JoinGroup)(nil),       // 0: JoinGroup
	(*BroadcastAll)(nil),    // 1: BroadcastAll
	(*BroadcastSector)(nil), // 2: BroadcastSector
	(*Echo)(nil),            // 3: Echo
	(*GroupMessage)(nil),    // 4: GroupMessage
}
var file_p3_proto_depIdxs = []int32{
	0, // 0: GroupMessage.joinGroup:type_name -> JoinGroup
	1, // 1: GroupMessage.broadcastAll:type_name -> BroadcastAll
	2, // 2: GroupMessage.broadcastSector:type_name -> BroadcastSector
	3, // 3: GroupMessage.echo:type_name -> Echo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_p3_proto_init() }
func file_p3_proto_init() {
	if File_p3_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_p3_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p3_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastAll); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p3_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastSector); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p3_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Echo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p3_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_p3_proto_msgTypes[4].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_p3_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_p3_proto_goTypes,
		DependencyIndexes: file_p3_proto_depIdxs,
		MessageInfos:      file_p3_proto_msgTypes,
	}.Build()
	File_p3_proto = out.File
	file_p3_proto_rawDesc = nil
	file_p3_proto_goTypes = nil
	file_p3_proto_depIdxs = nil
}
