package alttp

var (
	vanillaBottleItemNames = []string{"Shroom", "Empty Bottle", "Red Potion", "Green Potion", "Blue Potion", "Fairy", "Bee", "Good Bee"}

	vanillaItemNames = map[uint16][]string{
		0x340: {"Bow", "Bow", "Silver Bow", "Silver Bow"},
		0x341: {"Blue Boomerang", "Red Boomerang"},
		0x342: {"Hookshot"},
		0x344: {"Mushroom", "Magic Powder"},
		0x34C: {"Shovel", "Flute", "Flute (activated)"},
		0x345: {"Fire Rod"},
		0x346: {"Ice Rod"},
		0x347: {"Bombos Medallion"},
		0x348: {"Ether Medallion"},
		0x349: {"Quake Medallion"},
		0x34A: {"Lamp"},
		0x34B: {"Hammer"},
		0x34D: {"Bug Catching Net"},
		0x34E: {"Book of Mudora"},
		0x350: {"Cane of Somaria"},
		0x351: {"Cane of Byrna"},
		0x352: {"Magic Cape"},
		0x353: {"Magic Scroll", "Magic Mirror"},
		0x354: {"Power Gloves", "Titan's Mitts"},
		0x355: {"Pegasus Boots"},
		0x356: {"Flippers"},
		0x357: {"Moon Pearl"},
		0x359: {"Fighter Sword", "Master Sword", "Tempered Sword", "Golden Sword"},
		0x35A: {"Blue Shield", "Red Shield", "Mirror Shield"},
		0x35B: {"Blue Mail", "Red Mail"},
		0x35C: vanillaBottleItemNames,
		0x35D: vanillaBottleItemNames,
		0x35E: vanillaBottleItemNames,
		0x35F: vanillaBottleItemNames,
		0x37B: {"1/2 Magic", "1/4 Magic"},
	}

	vanillaQuantityNames = map[uint16]string{
		0x36C: "heart containers",
		0x370: "bomb capacity",
		0x371: "arrow capacity",
	}

	vanillaItemBitNames = map[uint16][]string{
		0x364: {
			"",
			"",
			"Ganon's Tower Compass",
			"Turtle Rock Compass",
			"Thieves Town Compass",
			"Tower of Hera Compass",
			"Ice Palace Compass",
			"Skull Woods Compass"},
		0x365: {
			"Misery Mire Compass",
			"Dark Palace Compass",
			"Swamp Palace Compass",
			"Hyrule Castle 2 Compass",
			"Desert Palace Compass",
			"Eastern Palace Compass",
			"Hyrule Castle Compass",
			"Sewer Passage Compass"},
		0x366: {
			"",
			"",
			"Ganon's Tower Big Key",
			"Turtle Rock Big Key",
			"Thieves Town Big Key",
			"Tower of Hera Big Key",
			"Ice Palace Big Key",
			"Skull Woods Big Key"},
		0x367: {
			"Misery Mire Big Key",
			"Dark Palace Big Key",
			"Swamp Palace Big Key",
			"Hyrule Castle 2 Big Key",
			"Desert Palace Big Key",
			"Eastern Palace Big Key",
			"Hyrule Castle Big Key",
			"Sewer Passage Big Key"},
		0x368: {
			"",
			"",
			"Ganon's Tower Map",
			"Turtle Rock Map",
			"Thieves Town Map",
			"Tower of Hera Map",
			"Ice Palace Map",
			"Skull Woods Map"},
		0x369: {
			"Misery Mire Map",
			"Dark Palace Map",
			"Swamp Palace Map",
			"Hyrule Castle 2 Map",
			"Desert Palace Map",
			"Eastern Palace Map",
			"Hyrule Castle Map",
			"Sewer Passage Map"},
		0x374: {
			"Red Pendant",
			"Blue Pendant",
			"Green Pendant",
			"",
			"",
			"",
			"",
			""},
		0x379: {
			"",
			"Swim Ability",
			"Dash Ability",
			"Pull Ability",
			"",
			"Talk Ability",
			"Read Ability",
			""},
		0x37A: {
			"Crystal #6",
			"Crystal #1",
			"Crystal #5",
			"Crystal #7",
			"Crystal #2",
			"Crystal #4",
			"Crystal #3",
			""},
		0x3C7: {
			//"Map Marker at Castle",
			"Map Marker at Kakariko",
			"Map Marker at Sahasrahla",
			"Map Marker at Pendants",
			"Map Marker at Master Sword",
			"Map Marker at Agahnim Tower",
			"Map Marker at Darkness",
			"Map Marker at Crystals",
			"Map Marker at Ganon's Tower"},
	}
)
