name: Main

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  release:
    #runs-on: ubuntu-latest
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - run: cd webui/web && npm ci && npm run production

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@master
      with:
        version: latest
        args: release --snapshot --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
